services:
  age:
    image: apache/age
    container_name: age
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=agedb
    ports:
      - "5455:5432"
  age-viewer:
    image: bikashpdash/age-viewer
    container_name: age-viewer
    ports:
      - "3000:3000"
  
